// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPollutionService.proto

package grpc.DSCA;

public interface carMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double number = 1;</code>
   */
  double getNumber();
}
