// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPollutionService.proto

package grpc.DSCA;

public interface railMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:railMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double distanceRail = 1;</code>
   */
  double getDistanceRail();
}
