// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA;

public final class AirQualityServiceImpl {
  private AirQualityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexRankNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexRankNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexRankRating_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexRankRating_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GasType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GasType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AirQualityService.proto\" \n\017IndexRankNu" +
      "mber\022\r\n\005index\030\001 \001(\005\"#\n\017IndexRankRating\022\020" +
      "\n\010iRRating\030\001 \001(\t\"&\n\007GasType\022\016\n\006index2\030\001 " +
      "\001(\005\022\013\n\003gas\030\002 \001(\t\";\n\017PollutionResult\022\030\n\020c" +
      "oncentrateLevel\030\001 \001(\005\022\016\n\006result\030\002 \001(\002*\037\n" +
      "\tOperation\022\022\n\016MULTIPLICATION\020\0002\211\001\n\021airQu" +
      "alityService\022:\n\022getAirQualityIndex\022\020.Ind" +
      "exRankNumber\032\020.IndexRankRating\"\000\0228\n\024poll" +
      "utantCalculation\022\010.GasType\032\020.PollutionRe" +
      "sult\"\000(\0010\001B$\n\tgrpc.DSCAB\025AirQualityServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IndexRankNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IndexRankNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexRankNumber_descriptor,
        new java.lang.String[] { "Index", });
    internal_static_IndexRankRating_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IndexRankRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexRankRating_descriptor,
        new java.lang.String[] { "IRRating", });
    internal_static_GasType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GasType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GasType_descriptor,
        new java.lang.String[] { "Index2", "Gas", });
    internal_static_PollutionResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionResult_descriptor,
        new java.lang.String[] { "ConcentrateLevel", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
