// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPollutionService.proto

package grpc.DSCA;

public interface busMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:busMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double distance = 1;</code>
   */
  double getDistance();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
