// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPollutionService.proto

package grpc.DSCA;

public interface carMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *	double consumptionPerLtr = 2;
   * </pre>
   *
   * <code>double distanceTravelled = 1;</code>
   */
  double getDistanceTravelled();
}
