// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPollutionService.proto

package grpc.DSCA;

public interface carResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double emissions = 1;</code>
   */
  double getEmissions();
}
