// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA;

public interface PollutionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 concentrateLevel = 1;</code>
   */
  int getConcentrateLevel();

  /**
   * <code>float result = 2;</code>
   */
  float getResult();
}
