// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA1;

public interface GasTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GasType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index2 = 1;</code>
   */
  int getIndex2();

  /**
   * <code>string gas = 2;</code>
   */
  java.lang.String getGas();
  /**
   * <code>string gas = 2;</code>
   */
  com.google.protobuf.ByteString
      getGasBytes();
}
