// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA1;

public interface IndexRankNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexRankNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   */
  int getIndex();
}
