// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA1;

public interface IndexRankRatingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexRankRating)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string iRRating = 1;</code>
   */
  java.lang.String getIRRating();
  /**
   * <code>string iRRating = 1;</code>
   */
  com.google.protobuf.ByteString
      getIRRatingBytes();
}
