// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package grpc.DSCA1;

/**
 * Protobuf type {@code PollutionResult}
 */
public  final class PollutionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PollutionResult)
    PollutionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PollutionResult.newBuilder() to construct.
  private PollutionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PollutionResult() {
    concentrateLevel_ = 0;
    result_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PollutionResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            concentrateLevel_ = input.readInt32();
            break;
          }
          case 21: {

            result_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.DSCA1.AirQualityServiceImpl.internal_static_PollutionResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.DSCA1.AirQualityServiceImpl.internal_static_PollutionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.DSCA1.PollutionResult.class, grpc.DSCA1.PollutionResult.Builder.class);
  }

  public static final int CONCENTRATELEVEL_FIELD_NUMBER = 1;
  private int concentrateLevel_;
  /**
   * <code>int32 concentrateLevel = 1;</code>
   */
  public int getConcentrateLevel() {
    return concentrateLevel_;
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private float result_;
  /**
   * <code>float result = 2;</code>
   */
  public float getResult() {
    return result_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (concentrateLevel_ != 0) {
      output.writeInt32(1, concentrateLevel_);
    }
    if (result_ != 0F) {
      output.writeFloat(2, result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (concentrateLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, concentrateLevel_);
    }
    if (result_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.DSCA1.PollutionResult)) {
      return super.equals(obj);
    }
    grpc.DSCA1.PollutionResult other = (grpc.DSCA1.PollutionResult) obj;

    boolean result = true;
    result = result && (getConcentrateLevel()
        == other.getConcentrateLevel());
    result = result && (
        java.lang.Float.floatToIntBits(getResult())
        == java.lang.Float.floatToIntBits(
            other.getResult()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONCENTRATELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getConcentrateLevel();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getResult());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.DSCA1.PollutionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.DSCA1.PollutionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.DSCA1.PollutionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.DSCA1.PollutionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.DSCA1.PollutionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PollutionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PollutionResult)
      grpc.DSCA1.PollutionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.DSCA1.AirQualityServiceImpl.internal_static_PollutionResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.DSCA1.AirQualityServiceImpl.internal_static_PollutionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.DSCA1.PollutionResult.class, grpc.DSCA1.PollutionResult.Builder.class);
    }

    // Construct using grpc.DSCA1.PollutionResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      concentrateLevel_ = 0;

      result_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.DSCA1.AirQualityServiceImpl.internal_static_PollutionResult_descriptor;
    }

    @java.lang.Override
    public grpc.DSCA1.PollutionResult getDefaultInstanceForType() {
      return grpc.DSCA1.PollutionResult.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.DSCA1.PollutionResult build() {
      grpc.DSCA1.PollutionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.DSCA1.PollutionResult buildPartial() {
      grpc.DSCA1.PollutionResult result = new grpc.DSCA1.PollutionResult(this);
      result.concentrateLevel_ = concentrateLevel_;
      result.result_ = result_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.DSCA1.PollutionResult) {
        return mergeFrom((grpc.DSCA1.PollutionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.DSCA1.PollutionResult other) {
      if (other == grpc.DSCA1.PollutionResult.getDefaultInstance()) return this;
      if (other.getConcentrateLevel() != 0) {
        setConcentrateLevel(other.getConcentrateLevel());
      }
      if (other.getResult() != 0F) {
        setResult(other.getResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.DSCA1.PollutionResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.DSCA1.PollutionResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int concentrateLevel_ ;
    /**
     * <code>int32 concentrateLevel = 1;</code>
     */
    public int getConcentrateLevel() {
      return concentrateLevel_;
    }
    /**
     * <code>int32 concentrateLevel = 1;</code>
     */
    public Builder setConcentrateLevel(int value) {
      
      concentrateLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 concentrateLevel = 1;</code>
     */
    public Builder clearConcentrateLevel() {
      
      concentrateLevel_ = 0;
      onChanged();
      return this;
    }

    private float result_ ;
    /**
     * <code>float result = 2;</code>
     */
    public float getResult() {
      return result_;
    }
    /**
     * <code>float result = 2;</code>
     */
    public Builder setResult(float value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float result = 2;</code>
     */
    public Builder clearResult() {
      
      result_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PollutionResult)
  }

  // @@protoc_insertion_point(class_scope:PollutionResult)
  private static final grpc.DSCA1.PollutionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.DSCA1.PollutionResult();
  }

  public static grpc.DSCA1.PollutionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PollutionResult>
      PARSER = new com.google.protobuf.AbstractParser<PollutionResult>() {
    @java.lang.Override
    public PollutionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PollutionResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PollutionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PollutionResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.DSCA1.PollutionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

